In [3]:
import pandas as pd
ratings = pd.read_csv("ratings.csv")
movies = pd.read_csv("movies.csv")
df = pd.merge(ratings, movies, on="movieId")
df_final = df[['userId', 'movieId', 'rating', 'title', 'genres']]
df_final.to_csv("final_dataset.csv", index=False)
df=pd.read_csv("final_dataset.csv")
print(df.head().to_string(index=False))

 userId  movieId  rating                       title                                      genres
      1        1     4.0            Toy Story (1995) Adventure|Animation|Children|Comedy|Fantasy
      1        3     4.0     Grumpier Old Men (1995)                              Comedy|Romance
      1        6     4.0                 Heat (1995)                       Action|Crime|Thriller
      1       47     5.0 Seven (a.k.a. Se7en) (1995)                            Mystery|Thriller
      1       50     5.0  Usual Suspects, The (1995)                      Crime|Mystery|Thriller

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 5 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   userId   100836 non-null  int64
 1   movieId  100836 non-null  int64
 2   rating   100836 non-null  float64
 3   title    100836 non-null  object
 4   genres   100836 non-null  object
dtypes: float64(1), int64(2), object(2)
memory usage: 3.8+ MB

In [ ]:
df.value_counts("genres") ##How many times each value occurs

genres
Comedy                                                    7196
Drama                                                     6291
Comedy|Romance                                            3967
Comedy|Drama|Romance                                      3000
Comedy|Drama                                              2851
                                                          ...
Horror|Sci-Fi|Western                                        1
Fantasy|Mystery|Romance|Thriller                             1
Fantasy|Mystery|Western                                      1
Horror|Romance|Sci-Fi                                        1
Action|Adventure|Animation|Children|Comedy|Sci-Fi|IMAX       1
Name: count, Length: 951, dtype: int64

In [15]:
df.value_counts("rating")

rating
4.0    26818
3.0    20047
5.0    13211
3.5    13136
4.5     8551
2.0     7551
2.5     5550
1.0     2811
1.5     1791
0.5     1370
Name: count, dtype: int64

In [ ]:
df.nunique() ##unique values per column

userId      610
movieId    9724
rating       10
title      9719
genres      951
dtype: int64

In [7]:
user_movie_matrix = df.pivot_table(
    index='userId',
    columns='title',
    values='rating'
).fillna(0)
user_movie_matrix.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
user_similarity = cosine_similarity(user_movie_matrix)

user_similarity_df = pd.DataFrame(
    user_similarity,
    index=user_movie_matrix.index,
    columns=user_movie_matrix.index
)
user_similarity_df.head()

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
userId,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.027283,0.059720,0.194395,0.129080,0.128152,0.158744,0.136968,0.064263,0.016875,...,0.080554,0.164455,0.221486,0.070669,0.153625,0.164191,0.269389,0.291097,0.093572,0.145321
2,0.027283,1.000000,0.000000,0.003726,0.016614,0.025333,0.027585,0.027257,0.000000,0.067445,...,0.202671,0.016866,0.011997,0.000000,0.000000,0.028429,0.012948,0.046211,0.027565,0.102427
3,0.059720,0.000000,1.000000,0.002251,0.005020,0.003936,0.000000,0.004941,0.000000,0.000000,...,0.005048,0.004892,0.024992,0.000000,0.010694,0.012993,0.019247,0.021128,0.000000,0.032119
4,0.194395,0.003726,0.002251,1.000000,0.128659,0.088491,0.115120,0.062969,0.011361,0.031163,...,0.085938,0.128273,0.307973,0.052985,0.084584,0.200395,0.131746,0.149858,0.032198,0.107683
5,0.129080,0.016614,0.005020,0.128659,1.000000,0.300349,0.108342,0.429075,0.000000,0.030611,...,0.068048,0.418747,0.110148,0.258773,0.148758,0.106435,0.152866,0.135535,0.261232,0.060792

In [10]:
user_similarity_df.loc[1].sort_values(ascending=False).head(10)

userId
1      1.000000
266    0.357408
313    0.351562
368    0.345127
57     0.345034
91     0.334727
469    0.330664
39     0.329782
288    0.329700
452    0.328048
Name: 1, dtype: float64

In [ ]:

avg_rating = df.groupby('title')['rating'].mean()
rating_count = df.groupby('title')['rating'].count()
top_movies = pd.DataFrame({
    'avg_rating': avg_rating,
    'rating_count': rating_count
})
top_movies = top_movies[top_movies['rating_count'] > 50]
top_movies = top_movies.sort_values(by='avg_rating', ascending=False)
def get_top_movies_for_user(user_id, n=10):
    user_movies = user_movie_matrix.loc[user_id]
    watched_movies = user_movies[user_movies > 0].index
    filtered_movies = [
        movie for movie in top_movies.index
        if movie not in watched_movies
    ]
    return filtered_movies[:n]

In [58]:
def recommend_by_genre(movie_name, n=5):
    
    # Get genres of selected movie
    genre = df[df['title'] == movie_name]['genres'].values
    
    if len(genre) == 0:
        return []
    
    genre_list = set(genre[0].split('|'))  # convert to set

    # Function to count matching genres
    def match_count(x):
        movie_genres = set(x.split('|'))
        return len(genre_list.intersection(movie_genres))

    # Apply matching
    df['match_score'] = df['genres'].apply(match_count)

    # Keep only strong matches (>=2 genres common)
    similar_movies = df[df['match_score'] >= 2]

    # Remove same movie
    similar_movies = similar_movies[similar_movies['title'] != movie_name]

    # Sort by match score + rating
    similar_movies = similar_movies.sort_values(
        by=['match_score', 'rating'],
        ascending=False
    )

    return similar_movies['title'].drop_duplicates().head(n).tolist()

In [59]:
def recommend_movies(user_id, n=5):

    similar_users = user_similarity_df[user_id].sort_values(ascending=False)[1:6]

    user_movies = user_movie_matrix.loc[user_id]
    watched_movies = user_movies[user_movies > 0].index

    recommendations = {}

    for sim_user, similarity_score in similar_users.items():
        sim_user_movies = user_movie_matrix.loc[sim_user]

        for movie, rating in sim_user_movies.items():
            if movie not in watched_movies and rating > 0:
                if movie not in recommendations:
                    recommendations[movie] = similarity_score * rating
                else:
                    recommendations[movie] += similarity_score * rating

    sorted_movies = sorted(
        recommendations.items(),
        key=lambda x: x[1],
        reverse=True
    )

    return [movie[0] for movie in sorted_movies[:n]]

In [60]:
def full_recommendation(user_id):

    # Get one movie user watched
    user_movies = user_movie_matrix.loc[user_id]
    watched = user_movies[user_movies > 0].index
    
    if len(watched) == 0:
        return
    
    movie_name = watched[0]  # pick first movie

    print("🔥 Top Picks for You:")
    print(get_top_movies_for_user(user_id))

    print("\n🎯 Because you watched:", movie_name)
    print(recommend_by_genre(movie_name))

    print("\n👥 Users like you also watched:")
    print(recommend_movies(user_id))

In [61]:
full_recommendation(1)

🔥 Top Picks for You:
['Shawshank Redemption, The (1994)', 'Godfather, The (1972)', 'Cool Hand Luke (1967)', 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)', 'Rear Window (1954)', 'Godfather: Part II, The (1974)', 'Departed, The (2006)', 'Casablanca (1942)', 'Dark Knight, The (2008)', 'Chinatown (1974)']

🎯 Because you watched: 13th Warrior, The (1999)
['Princess Bride, The (1987)', 'Highlander (1986)', 'Conan the Barbarian (1982)', 'Goonies, The (1985)', 'Indiana Jones and the Temple of Doom (1984)']

👥 Users like you also watched:
['Aliens (1986)', 'Hunt for Red October, The (1990)', 'Blade Runner (1982)', 'Terminator 2: Judgment Day (1991)', 'Die Hard (1988)']